---
version: '3.8'

services:

  db:
    image: "mariadb:${MARIADB_VERSION}"
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d
    networks:
      - backend
    env_file:
      - .env

  memcached:
    image: memcached:alpine
    restart: always
    networks:
      - backend

  idoit:
    build: "./${IDOIT_VERSION}/${IDOIT_VARIANT}/php${PHP_VERSION}/apache/"
    restart: always
    volumes:
      - idoit:/var/www/html
    networks:
      - frontend
      - backend
    ports:
      - "${IDOIT_WEB_PORT}:80"
    depends_on:
      - db
      - memcached
    env_file:
      - .env

volumes:
  idoit:
  db:

networks:
  frontend:
  backend:
