---
version: '3.8'

services:

  db:
    image: "mariadb:${MARIADB_VERSION}"
    restart: always
    network_mode: none
    volumes:
      - db:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d
      - dbsocket:/run/mysqld
    env_file:
      - .env

  memcached:
    image: memcached:alpine
    restart: always
    network_mode: none
    volumes:
      - memcachedsocket:/tmp
    command: -s /tmp/memcached.sock -a 777

  web:
    build: ./apache-socket/
    restart: always
    networks:
      - frontend
    ports:
      - "${IDOIT_WEB_PORT}:80"
    depends_on:
      - idoit
    volumes:
      - fpmsocket:/run/php
      - type: volume
        source: idoit
        target: /var/www/html
        read_only: true
        volume:
          nocopy: true

  idoit:
    build: "./${IDOIT_VERSION}/${IDOIT_VARIANT}/php${PHP_VERSION}/fpm/"
    restart: always
    network_mode: none
    volumes:
      - idoit:/var/www/html
      - fpmsocket:/run/php
      - dbsocket:/run/mysqld
      - memcachedsocket:/run/memcached
    depends_on:
      - db
      - memcached
    env_file:
      - .env

volumes:
  idoit:
  db:
  dbsocket:
  fpmsocket:
  memcachedsocket:

networks:
  frontend:
